spring:
    config:
        import: classpath:/env.yml

    datasource:
        url: jdbc:mysql://localhost:3306/bssm_portfolio?useSSL=false&serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${db.mysql.username}
        password: ${db.mysql.password}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100
